# Generated by Django 5.2.15 on 2026-10-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('caso_nuevo', 'Caso nuevo'), ('analisis_completado', 'Análisis completado'), ('analisis_error', 'Análisis con error'), ('documento_nuevo', 'Documento nuevo'), ('caso_reasignado', 'Caso reasignado')], max_length=30),
        ),
    ]
