# Generated by Django 5.2.15 on 2026-06-30 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_articulo', models.CharField(max_length=50)),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('contenido', models.TextField()),
                ('jerarquia_normativa', models.FloatField(default=0.8, help_text='Valor 0-1 según jerarquía. Constitución=1.0, Código=0.8')),
                ('frecuencia_historica', models.IntegerField(default=0, help_text='Veces seleccionado en casos anteriores')),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'articulos',
                'ordering': ['norma', 'numero_articulo'],
            },
        ),
        migrations.CreateModel(
            name='EntidadJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entidades_juridicas',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['estado'], name='idx_entidades_estado')],
            },
        ),
        migrations.CreateModel(
            name='ArticuloEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_catalogo.articulo')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_catalogo.entidadjuridica')),
            ],
            options={
                'db_table': 'articulo_entidades',
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='entidades',
            field=models.ManyToManyField(blank=True, related_name='articulos', through='modulo_catalogo.ArticuloEntidad', to='modulo_catalogo.entidadjuridica'),
        ),
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('sigla', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'normas',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['estado'], name='idx_normas_estado'), models.Index(fields=['sigla'], name='idx_normas_sigla')],
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='norma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='modulo_catalogo.norma'),
        ),
        migrations.CreateModel(
            name='RamaDerecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ramas_derecho',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['estado'], name='idx_ramas_estado')],
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='rama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='modulo_catalogo.ramaderecho'),
        ),
        migrations.AddIndex(
            model_name='articuloentidad',
            index=models.Index(fields=['articulo'], name='idx_art_entidades_art'),
        ),
        migrations.AddIndex(
            model_name='articuloentidad',
            index=models.Index(fields=['entidad'], name='idx_art_entidades_entid'),
        ),
        migrations.AlterUniqueTogether(
            name='articuloentidad',
            unique_together={('articulo', 'entidad')},
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['norma'], name='idx_articulos_norma'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['rama'], name='idx_articulos_rama'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['estado'], name='idx_articulos_estado'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['-frecuencia_historica'], name='idx_articulos_frecuencia'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['numero_articulo'], name='idx_articulos_numero'),
        ),
    ]
