# Generated by Django 5.2.15 on 2026-08-27 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jerarquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('nivel', models.PositiveIntegerField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'jerarquias',
                'ordering': ['nivel'],
            },
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='jerarquia_normativa',
        ),
        migrations.AddField(
            model_name='norma',
            name='jerarquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='normas', to='modulo_catalogo.jerarquia'),
        ),
        migrations.AddIndex(
            model_name='norma',
            index=models.Index(fields=['jerarquia'], name='idx_normas_jerarquia'),
        ),
    ]
