# Generated by Django 5.2.15 on 2026-10-03 00:45

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_catalogo', '0009_documentonorma_vigente'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='articulo',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('titulo'), name='gin_trgm_ops'), name='idx_art_titulo_trgm'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('contenido'), name='gin_trgm_ops'), name='idx_art_contenido_trgm'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('numero_articulo'), name='gin_trgm_ops'), name='idx_art_numero_trgm'),
        ),
    ]
