# Generated by Django 5.2.15 on 2026-10-03 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_catalogo', '0010_articulo_idx_art_titulo_trgm_and_more'),
        ('modulo_catalogo', '0010_busqueda_trigramas_articulos'),
    ]

    # Ambas ramas crean los mismos índices con nombres distintos. Los
    # idx_art_* están declarados en el estado de Django; conservarlos evita
    # mantener dos GIN equivalentes al insertar o actualizar artículos.
    operations = [
        migrations.RunSQL(
            sql=f'DROP INDEX IF EXISTS {nombre};',
            reverse_sql=f'CREATE INDEX IF NOT EXISTS {nombre} '
                        f'ON articulos USING gin (UPPER({campo}) gin_trgm_ops);',
        )
        for nombre, campo in [
            ('idx_articulos_contenido_trgm', 'contenido'),
            ('idx_articulos_titulo_trgm', 'titulo'),
            ('idx_articulos_numero_trgm', 'numero_articulo'),
        ]
    ]
