# Generated by Django 5.2.15 on 2026-10-03 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_catalogo', '0011_merge_20261003_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='documento_norma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos_fuente', to='modulo_catalogo.documentonorma'),
        ),
    ]
