# Generated by Django 5.2.15 on 2026-10-03 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_catalogo', '0012_articulo_documento_norma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='avisos_vigencia',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='articulo',
            name='tipo_unidad',
            field=models.CharField(default='articulo', max_length=30),
        ),
        migrations.AddField(
            model_name='documentonorma',
            name='analisis_normativo',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='documentonorma',
            name='metadatos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='documentonorma',
            name='url_fuente',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='norma',
            name='avisos_vigencia',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='norma',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='norma',
            name='numero_norma',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='norma',
            name='tipo_norma',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='DocumentoOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_fuente', models.URLField(max_length=1000, unique=True)),
                ('url_pdf', models.URLField(max_length=1000)),
                ('identificador', models.CharField(max_length=80)),
                ('titulo', models.CharField(max_length=500)),
                ('tipo', models.CharField(blank=True, max_length=80)),
                ('numero', models.CharField(blank=True, max_length=50)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('texto', models.TextField(blank=True)),
                ('ruta_archivo', models.CharField(blank=True, max_length=1000)),
                ('hash_pdf', models.CharField(blank=True, max_length=64)),
                ('penal', models.BooleanField(default=False)),
                ('estado_descarga', models.CharField(default='pendiente', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('ultima_consulta', models.DateTimeField(auto_now=True)),
                ('documento_catalogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origenes_oficiales', to='modulo_catalogo.documentonorma')),
            ],
            options={
                'ordering': ['-fecha_publicacion', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='CambioNormativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacion', models.CharField(choices=[('abroga', 'abroga'), ('deroga', 'deroga'), ('modifica', 'modifica'), ('incorpora', 'incorpora'), ('general', 'general'), ('temporal', 'temporal')], max_length=20)),
                ('estado_revision', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('descartado', 'Descartado')], default='pendiente', max_length=20)),
                ('unidad_fuente', models.CharField(blank=True, max_length=80)),
                ('referencia', models.JSONField(default=dict)),
                ('cita', models.TextField()),
                ('origen', models.CharField(default='clausula', max_length=30)),
                ('norma_causante', models.CharField(blank=True, max_length=200)),
                ('fecha_norma_causante', models.DateField(blank=True, null=True)),
                ('fecha_efecto', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('huella', models.CharField(max_length=64, unique=True)),
                ('revisado_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('articulo_afectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambios_recibidos', to='modulo_catalogo.articulo')),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_detectados', to='modulo_catalogo.documentonorma')),
                ('norma_afectada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambios_recibidos', to='modulo_catalogo.norma')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['estado_revision'], name='idx_cambio_revision')],
            },
        ),
        migrations.CreateModel(
            name='VersionArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=500)),
                ('contenido', models.TextField()),
                ('huella', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='modulo_catalogo.articulo')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modulo_catalogo.documentonorma')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('articulo', 'huella'), name='version_articulo_unica')],
            },
        ),
    ]
