# Generated by Django 5.2.15 on 2026-10-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_catalogo', '0013_vigencia_normativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='norma',
            name='fecha_norma',
            field=models.DateField(blank=True, null=True),
        ),
    ]
