# Generated by Django 5.2.15 on 2026-10-03 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_catalogo', '0014_fecha_norma'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposicionNormativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=80)),
                ('tipo', models.CharField(choices=[('final', 'Final'), ('derogatoria', 'Derogatoria'), ('abrogatoria', 'Abrogatoria')], max_length=30)),
                ('titulo', models.CharField(blank=True, max_length=500)),
                ('contenido', models.TextField()),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposiciones', to='modulo_catalogo.documentonorma')),
            ],
            options={
                'db_table': 'disposiciones_normativas',
                'ordering': ['documento_id', 'id'],
                'constraints': [models.UniqueConstraint(fields=('documento', 'numero'), name='disposicion_documento_unica')],
            },
        ),
    ]
