# Generated by Django 5.2.15 on 2026-10-06 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_catalogo', '0016_separar_disposiciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=500)),
                ('texto_antes', models.TextField()),
                ('texto_despues', models.TextField()),
                ('parte_afectada', models.JSONField(default=dict)),
                ('aplicado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_cambios', to='modulo_catalogo.articulo')),
                ('cambio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_articulos', to='modulo_catalogo.cambionormativo')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('cambio', 'articulo'), name='historial_cambio_articulo_unico')],
            },
        ),
    ]
