"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv  
from datetime import timedelta
from decouple import config, Csv



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
ENCRYPTION_KEY = os.getenv("ENCRYPTION_KEY")
DEBUG = True

ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1"
).split(",")

CORS_ALLOWED_ORIGINS = os.getenv(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:5173"
).split(",")

CORS_ALLOW_CREDENTIALS = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #modulos
    'modulo_auditoria',
    'modulo_casos',
    'modulo_catalogo',
    'modulo_clientes',
    'modulo_documentos',
    'modulo_ia',
    'modulo_usuarios',

    "corsheaders",

    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",

    "drf_spectacular",
    "pgvector",

]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE"),
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    # Cada refresh emite un token nuevo y blacklistea el anterior: si un
    # refresh token es robado (ej. filtrado en un log), su ventana de uso
    # útil se acorta a la próxima vez que el usuario legítimo lo use.
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,

    # Muy importante si tu login devuelve access_token y refresh_token
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# ---------------------------------------------------------------------
# Cookie httpOnly del refresh token
# ---------------------------------------------------------------------
# El refresh token NUNCA viaja en el body de la respuesta ni se guarda
# en localStorage: se setea como cookie httpOnly desde LoginView /
# RefreshTokenView (ver modulo_usuarios/views/auth_view.py). Así un XSS
# en el frontend no puede leerlo con document.cookie ni localStorage.
REFRESH_TOKEN_COOKIE_NAME     = "refresh_token"
REFRESH_TOKEN_COOKIE_PATH     = "/api/usuarios/auth/"
REFRESH_TOKEN_COOKIE_SAMESITE = "Lax"
# Secure=True exige HTTPS. En desarrollo local (DEBUG=True, http://localhost)
# se desactiva para que la cookie se siga guardando sin TLS.
REFRESH_TOKEN_COOKIE_SECURE   = not DEBUG

AUTH_USER_MODEL = "modulo_usuarios.Usuario"
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------
# Correo (Gmail SMTP)
# ---------------------------------------------------------------------
# Se usa para enviar al usuario nuevo su usuario y contraseña temporal
# al crearse la cuenta (ver core/utils/emails.py).
#
# EMAIL_HOST_USER    : la cuenta de Gmail que envía el correo.
# EMAIL_HOST_PASSWORD: una "contraseña de aplicación" de Gmail, NO la
#                      contraseña normal de la cuenta (Gmail exige 2FA
#                      activado para generar una en
#                      https://myaccount.google.com/apppasswords).
#
# En desarrollo, si no se configuran estas variables, se usa la
# consola como backend: los correos se imprimen en la terminal en vez
# de enviarse de verdad, para poder probar el flujo sin credenciales.
EMAIL_HOST_USER     = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST    = "smtp.gmail.com"
    EMAIL_PORT    = 587
    EMAIL_USE_TLS = True
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "no-reply@jurisia.local")

# ---------------------------------------------------------------------
# Recuperación de contraseña por correo
# ---------------------------------------------------------------------
# El flujo actual NO usa enlaces: al pedir la recuperación se genera
# una contraseña temporal nueva y se manda por Gmail (mismo mecanismo
# que al crear un usuario). FRONTEND_URL queda declarado por si algún
# día se vuelve a necesitar armar un link (o para otros usos del
# frontend), pero el flujo de recuperación ya no lo consume.
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:5173")

# Minutos de vigencia del token de recuperación antes de expirar.
PASSWORD_RESET_VIGENCIA_MINUTOS = int(os.getenv("PASSWORD_RESET_VIGENCIA_MINUTOS", "30"))

# Máximo de solicitudes de recuperación que se atienden para el mismo
# usuario dentro de PASSWORD_RESET_VENTANA_MINUTOS. Evita que alguien
# spamee de correos de recuperación a una cuenta ajena; la respuesta
# HTTP sigue siendo la misma igual (genérica) para no filtrar si el
# límite se alcanzó o no.
PASSWORD_RESET_MAX_SOLICITUDES = int(os.getenv("PASSWORD_RESET_MAX_SOLICITUDES", "3"))
PASSWORD_RESET_VENTANA_MINUTOS = int(os.getenv("PASSWORD_RESET_VENTANA_MINUTOS", "60"))

# ---------------------------------------------------------------------
# Bloqueo temporal de login por intentos fallidos
# ---------------------------------------------------------------------
# Después de LOGIN_MAX_INTENTOS contraseñas incorrectas seguidas para
# el mismo usuario, la cuenta queda bloqueada por LOGIN_BLOQUEO_MINUTOS
# minutos (ver LoginSerializer.validate en auth_serializer.py). Un
# admin puede destrabarla antes desde POST /api/usuarios/{id}/desbloquear/.
LOGIN_MAX_INTENTOS    = int(os.getenv("LOGIN_MAX_INTENTOS", "5"))
LOGIN_BLOQUEO_MINUTOS = int(os.getenv("LOGIN_BLOQUEO_MINUTOS", "15"))

SENTENCE_TRANSFORMER_MODEL = config(
    'SENTENCE_TRANSFORMER_MODEL',
    default='sentence-transformers/paraphrase-multilingual-mpnet-base-v2'
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "file": {
            "class": "logging.FileHandler",
            "filename": "logs/django.log",
        },
    },
    "root": {
        "handlers": ["file"],
        "level": "INFO",
    },
}

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",

    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),

    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}