# Generated by Django 5.2.15 on 2026-06-30 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_casos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_doc',
            },
        ),
        migrations.CreateModel(
            name='PlantillaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ruta_archivo', models.CharField(help_text='Ruta relativa en MEDIA_ROOT/plantillas/', max_length=255)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantillas', to='modulo_documentos.tipodoc')),
            ],
            options={
                'db_table': 'plantillas_documento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_original', models.CharField(max_length=500)),
                ('ruta_archivo', models.CharField(max_length=1000)),
                ('tipo_archivo', models.CharField(help_text='pdf, docx, jpg, etc.', max_length=50)),
                ('tamano', models.BigIntegerField(help_text='Tamaño en bytes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='modulo_casos.caso')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_caso', to='modulo_documentos.tipodoc')),
            ],
            options={
                'db_table': 'documentos_caso',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_archivo', models.CharField(max_length=255)),
                ('hash_archivo', models.CharField(blank=True, help_text='SHA-256 del archivo para verificar integridad.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_generados', to='modulo_casos.caso')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_generados', to='modulo_documentos.plantilladocumento')),
            ],
            options={
                'db_table': 'documentos_generados',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['caso'], name='idx_docs_gen_caso'), models.Index(fields=['plantilla'], name='idx_docs_gen_plantilla'), models.Index(fields=['hash_archivo'], name='idx_docs_gen_hash')],
            },
        ),
        migrations.AddIndex(
            model_name='plantilladocumento',
            index=models.Index(fields=['tipo_documento'], name='idx_plantillas_tipo'),
        ),
        migrations.AddIndex(
            model_name='documentocaso',
            index=models.Index(fields=['caso'], name='idx_docs_caso'),
        ),
        migrations.AddIndex(
            model_name='documentocaso',
            index=models.Index(fields=['tipo_documento'], name='idx_docs_tipo'),
        ),
        migrations.AddIndex(
            model_name='documentocaso',
            index=models.Index(fields=['-created_at'], name='idx_docs_created'),
        ),
    ]
