# Generated by Django 5.2.15 on 2026-10-03 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextoDocumentoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_pdf', models.CharField(max_length=64)),
                ('version_extractor', models.CharField(max_length=100)),
                ('texto', models.TextField(blank=True)),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modulo_documentos.documentocaso')),
            ],
            options={
                'db_table': 'textos_documentos_caso',
            },
        ),
    ]
