# Generated by Django 5.2.15 on 2026-07-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.TextField(blank=True, null=True),
        ),
    ]
