# Generated by Django 5.2.15 on 2026-07-20 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_clientes', '0002_cliente_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_nacimiento',
        ),
    ]
