# Generated by Django 5.2.15 on 2026-06-30 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(max_length=100)),
                ('accion', models.CharField(choices=[('CREATE', 'Creación'), ('READ', 'Lectura'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('EXPORT', 'Exportación'), ('ANALYZE', 'Análisis IA')], max_length=50)),
                ('registro_id', models.BigIntegerField(blank=True, help_text='ID del registro afectado.', null=True)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Contexto adicional: valores anteriores, payload, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditoria', to='modulo_usuarios.usuario')),
            ],
            options={
                'db_table': 'auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario'], name='idx_auditoria_usuario'), models.Index(fields=['tabla'], name='idx_auditoria_tabla'), models.Index(fields=['accion'], name='idx_auditoria_accion'), models.Index(fields=['-created_at'], name='idx_auditoria_created'), models.Index(fields=['tabla', 'registro_id'], name='idx_auditoria_registro')],
            },
        ),
    ]
