# Generated by Django 5.2.15 on 2026-08-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoria',
            options={'ordering': ['-created_at'], 'verbose_name': 'Registro de auditoría', 'verbose_name_plural': 'Registros de auditoría'},
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='ip',
            field=models.GenericIPAddressField(blank=True, help_text='Dirección IP (IPv4 o IPv6) desde donde se originó la acción.', null=True),
        ),
    ]
