# Generated by Django 5.2.15 on 2026-06-30 00:57

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_casos', '0001_initial'),
        ('modulo_catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('orden', models.PositiveIntegerField(help_text='Posición del chunk dentro del caso.')),
                ('tipo', models.CharField(choices=[('texto', 'Texto redactado'), ('pdf', 'Extraído de PDF')], default='texto', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='modulo_casos.caso')),
            ],
            options={
                'db_table': 'chunks_caso',
                'ordering': ['caso', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='EmbeddingArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', pgvector.django.vector.VectorField(dimensions=768, help_text='Embedding 768-dim (all-mpnet-base-v2).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='modulo_catalogo.articulo')),
            ],
            options={
                'db_table': 'embeddings_articulos',
            },
        ),
        migrations.CreateModel(
            name='EmbeddingChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', pgvector.django.vector.VectorField(dimensions=768)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='modulo_ia.chunkcaso')),
            ],
            options={
                'db_table': 'embeddings_chunk',
            },
        ),
        migrations.CreateModel(
            name='EntidadDetectadaCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_detectado', models.CharField(max_length=255)),
                ('score', models.FloatField(default=0.0)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidades_detectadas', to='modulo_ia.chunkcaso')),
            ],
            options={
                'db_table': 'entidades_detectadas_caso',
            },
        ),
        migrations.CreateModel(
            name='ResultadoArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_total', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('score_semantico', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('score_delito', models.DecimalField(decimal_places=6, default=0, help_text='Coincidencia de delito/derecho identificado.', max_digits=10)),
                ('score_entidades', models.DecimalField(decimal_places=6, default=0, help_text='Coincidencia de entidades jurídicas.', max_digits=10)),
                ('score_jerarquia', models.DecimalField(decimal_places=6, default=0, help_text='Jerarquía normativa del artículo.', max_digits=10)),
                ('score_frecuencia', models.DecimalField(decimal_places=6, default=0, help_text='Frecuencia histórica normalizada.', max_digits=10)),
                ('posicion', models.PositiveIntegerField(help_text='Posición en el ranking.')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='modulo_catalogo.articulo')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_articulos', to='modulo_casos.caso')),
            ],
            options={
                'db_table': 'resultado_articulos',
                'ordering': ['caso', 'posicion'],
            },
        ),
        migrations.AddIndex(
            model_name='chunkcaso',
            index=models.Index(fields=['caso'], name='idx_chunks_caso'),
        ),
        migrations.AddIndex(
            model_name='chunkcaso',
            index=models.Index(fields=['caso', 'orden'], name='idx_chunks_orden'),
        ),
        migrations.AddIndex(
            model_name='chunkcaso',
            index=models.Index(fields=['tipo'], name='idx_chunks_tipo'),
        ),
        migrations.AddIndex(
            model_name='embeddingarticulo',
            index=models.Index(fields=['articulo'], name='idx_emb_art_articulo'),
        ),
        migrations.AddIndex(
            model_name='embeddingchunk',
            index=models.Index(fields=['chunk'], name='idx_emb_chunk_chunk'),
        ),
        migrations.AddIndex(
            model_name='entidaddetectadacaso',
            index=models.Index(fields=['chunk'], name='idx_entdet_chunk'),
        ),
        migrations.AddIndex(
            model_name='entidaddetectadacaso',
            index=models.Index(fields=['-score'], name='idx_entdet_score'),
        ),
        migrations.AddIndex(
            model_name='resultadoarticulo',
            index=models.Index(fields=['caso'], name='idx_resultado_caso'),
        ),
        migrations.AddIndex(
            model_name='resultadoarticulo',
            index=models.Index(fields=['articulo'], name='idx_resultado_articulo'),
        ),
        migrations.AddIndex(
            model_name='resultadoarticulo',
            index=models.Index(fields=['caso', '-score_total'], name='idx_resultado_score'),
        ),
        migrations.AddIndex(
            model_name='resultadoarticulo',
            index=models.Index(fields=['caso', 'posicion'], name='idx_resultado_posicion'),
        ),
        migrations.AlterUniqueTogether(
            name='resultadoarticulo',
            unique_together={('caso', 'articulo')},
        ),
    ]
