# Generated by Django 5.2.15 on 2026-08-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoarticulo',
            name='es_sugerencia',
            field=models.BooleanField(default=False, help_text='True si el artículo se incluyó como sugerencia complementaria (ej. figura transversal como tentativa, legítima defensa) en vez de haber superado el umbral principal de relevancia por mérito propio.'),
        ),
    ]
