# Generated by hand — ver modulo_ia/services/model_loader.py y
# modulo_ia/models/embedding.py para el porqué de este cambio.
import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


def _backfill_modelo_version(apps, schema_editor):
    """
    Los embeddings que ya existían antes de este versionado se generaron
    con lo que en ese momento era settings.EMBEDDING_MODEL_VERSION — se
    les asigna esa etiqueta ahora para no perder de qué modelo salieron.
    """
    version_actual = settings.EMBEDDING_MODEL_VERSION
    EmbeddingArticulo = apps.get_model("modulo_ia", "EmbeddingArticulo")
    EmbeddingChunk = apps.get_model("modulo_ia", "EmbeddingChunk")
    EmbeddingArticulo.objects.filter(modelo_version="").update(modelo_version=version_actual)
    EmbeddingChunk.objects.filter(modelo_version="").update(modelo_version=version_actual)


class Migration(migrations.Migration):

    dependencies = [
        ("modulo_catalogo", "0001_initial"),
        ("modulo_ia", "0002_resultadoarticulo_es_sugerencia"),
    ]

    operations = [
        # OneToOneField -> ForeignKey: mismo campo/columna, se conservan los
        # datos existentes; solo cambia related_name y se deja de exigir
        # unicidad simple (la unicidad pasa a ser compuesta con modelo_version).
        migrations.AlterField(
            model_name="embeddingarticulo",
            name="articulo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embeddings",
                to="modulo_catalogo.articulo",
            ),
        ),
        migrations.AlterField(
            model_name="embeddingchunk",
            name="chunk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embeddings",
                to="modulo_ia.chunkcaso",
            ),
        ),

        migrations.AddField(
            model_name="embeddingarticulo",
            name="modelo_version",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="embeddingchunk",
            name="modelo_version",
            field=models.CharField(default="", max_length=100),
        ),

        migrations.RunPython(_backfill_modelo_version, migrations.RunPython.noop),

        migrations.AlterField(
            model_name="embeddingarticulo",
            name="modelo_version",
            field=models.CharField(
                help_text="Etiqueta de la versión de modelo con la que se generó "
                           "este vector (ver settings.EMBEDDING_MODEL_VERSION).",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="embeddingchunk",
            name="modelo_version",
            field=models.CharField(max_length=100),
        ),

        migrations.AlterField(
            model_name="embeddingarticulo",
            name="vector",
            field=pgvector.django.vector.VectorField(dimensions=768, help_text="Embedding 768-dim."),
        ),

        migrations.AddIndex(
            model_name="embeddingarticulo",
            index=models.Index(fields=["modelo_version"], name="idx_emb_art_version"),
        ),
        migrations.AddIndex(
            model_name="embeddingchunk",
            index=models.Index(fields=["modelo_version"], name="idx_emb_chunk_version"),
        ),
        migrations.AddConstraint(
            model_name="embeddingarticulo",
            constraint=models.UniqueConstraint(
                fields=("articulo", "modelo_version"), name="uq_embedding_articulo_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="embeddingchunk",
            constraint=models.UniqueConstraint(
                fields=("chunk", "modelo_version"), name="uq_embedding_chunk_version"
            ),
        ),
    ]
