# Generated by Django 5.2.15 on 2026-10-08 16:36

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_casos', '0009_resultadocaso_jurisprudencia_estado_and_more'),
        ('modulo_ia', '0005_ranking_vigencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolucionJurisprudencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente_id', models.CharField(max_length=40, unique=True)),
                ('numero', models.CharField(blank=True, max_length=150)),
                ('expediente', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('materia', models.CharField(default='Penal', max_length=150)),
                ('sala', models.CharField(blank=True, max_length=255)),
                ('departamento', models.CharField(blank=True, max_length=150)),
                ('url_fuente', models.URLField(max_length=1000)),
                ('url_pdf', models.URLField(blank=True, max_length=2000)),
                ('texto', models.TextField()),
                ('huella', models.CharField(max_length=64)),
                ('activa', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jurisprudencia_resoluciones',
            },
        ),
        migrations.CreateModel(
            name='FragmentoJurisprudencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('contenido', models.TextField()),
                ('resolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragmentos', to='modulo_ia.resolucionjurisprudencia')),
            ],
            options={
                'db_table': 'jurisprudencia_fragmentos',
            },
        ),
        migrations.CreateModel(
            name='ResultadoJurisprudencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveIntegerField()),
                ('score_semantico', models.FloatField()),
                ('fragmento', models.TextField(help_text='Copia del fragmento que justificó la coincidencia.')),
                ('huella_fuente', models.CharField(max_length=64)),
                ('modelo_version', models.CharField(max_length=100)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_jurisprudencia', to='modulo_casos.caso')),
                ('resolucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='modulo_ia.resolucionjurisprudencia')),
            ],
            options={
                'db_table': 'jurisprudencia_resultados',
                'ordering': ['posicion'],
            },
        ),
        migrations.CreateModel(
            name='EmbeddingJurisprudencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_version', models.CharField(db_index=True, max_length=100)),
                ('vector', pgvector.django.vector.VectorField(dimensions=768)),
                ('fragmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='modulo_ia.fragmentojurisprudencia')),
            ],
            options={
                'db_table': 'jurisprudencia_embeddings',
                'constraints': [models.UniqueConstraint(fields=('fragmento', 'modelo_version'), name='uq_juris_embedding_version')],
            },
        ),
        migrations.AddConstraint(
            model_name='fragmentojurisprudencia',
            constraint=models.UniqueConstraint(fields=('resolucion', 'orden'), name='uq_juris_fragmento_orden'),
        ),
        migrations.AddConstraint(
            model_name='resultadojurisprudencia',
            constraint=models.UniqueConstraint(fields=('caso', 'resolucion'), name='uq_juris_resultado_caso'),
        ),
    ]
