# Generated by Django 5.2.15 on 2026-10-09 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_casos', '0009_resultadocaso_jurisprudencia_estado_and_more'),
        ('modulo_catalogo', '0019_rutas_portables_documentos'),
        ('modulo_ia', '0006_resolucionjurisprudencia_fragmentojurisprudencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoarticulo',
            name='modelo_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='ValoracionArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(choices=[('util', 'Útil'), ('no_util', 'No útil'), ('sin_valorar', 'Sin valorar')], max_length=12)),
                ('contexto_hash', models.CharField(max_length=64)),
                ('modelo_version', models.CharField(blank=True, max_length=100)),
                ('muestra', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modulo_catalogo.articulo')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_casos.caso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['caso', 'usuario'], name='idx_valoracion_caso_usuario')],
            },
        ),
    ]
