# Generated by Django 5.2.15 on 2026-10-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ia', '0007_resultadoarticulo_modelo_version_valoracionarticulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoarticulo',
            name='contexto_evaluado',
            field=models.JSONField(default=dict),
        ),
    ]
