# Generated by Django 5.2.15 on 2026-10-11 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_casos', '0010_identificadores_publicos'),
        ('modulo_ia', '0011_indices_jurisprudencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadojurisprudencia',
            name='contexto_evaluado',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='ValoracionJurisprudencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(choices=[('util', 'Útil'), ('no_util', 'No útil'), ('sin_valorar', 'Sin valorar')], max_length=12)),
                ('contexto_hash', models.CharField(max_length=64)),
                ('modelo_version', models.CharField(blank=True, max_length=100)),
                ('muestra', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_casos.caso')),
                ('resolucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modulo_ia.resolucionjurisprudencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['caso', 'resolucion', '-id'], name='idx_val_juris_caso_resolucion')],
            },
        ),
    ]
