# Generated by Django 5.2.15 on 2026-06-30 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_catalogo', '0001_initial'),
        ('modulo_clientes', '0001_initial'),
        ('modulo_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hechos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Petitorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'petitorios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('titulo', models.CharField(max_length=500)),
                ('descripcion', models.TextField(blank=True, help_text='Texto redactado del caso. Vacío si se subió PDF.', null=True)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos', to='modulo_clientes.cliente')),
                ('rama_detectada', models.ForeignKey(blank=True, help_text='Rama jurídica detectada por el análisis IA.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos', to='modulo_catalogo.ramaderecho')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos', to='modulo_usuarios.usuario')),
            ],
            options={
                'db_table': 'casos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HechoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden del hecho dentro del caso.')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hechos_caso', to='modulo_casos.caso')),
                ('hecho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_hecho', to='modulo_casos.hecho')),
            ],
            options={
                'db_table': 'hechos_casos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PetitorioCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petitorios_caso', to='modulo_casos.caso')),
                ('petitorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_petitorio', to='modulo_casos.petitorio')),
            ],
            options={
                'db_table': 'petitorios_casos',
            },
        ),
        migrations.CreateModel(
            name='ResultadoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen', models.TextField(blank=True, null=True)),
                ('fortalezas', models.TextField(blank=True, null=True)),
                ('debilidades', models.TextField(blank=True, null=True)),
                ('estrategias', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='modulo_casos.caso')),
            ],
            options={
                'db_table': 'resultados_caso',
            },
        ),
        migrations.AddIndex(
            model_name='caso',
            index=models.Index(fields=['usuario'], name='idx_casos_usuario'),
        ),
        migrations.AddIndex(
            model_name='caso',
            index=models.Index(fields=['cliente'], name='idx_casos_cliente'),
        ),
        migrations.AddIndex(
            model_name='caso',
            index=models.Index(fields=['rama_detectada'], name='idx_casos_rama'),
        ),
        migrations.AddIndex(
            model_name='caso',
            index=models.Index(fields=['estado'], name='idx_casos_estado'),
        ),
        migrations.AddIndex(
            model_name='caso',
            index=models.Index(fields=['codigo'], name='idx_casos_codigo'),
        ),
        migrations.AddIndex(
            model_name='caso',
            index=models.Index(fields=['-created_at'], name='idx_casos_created'),
        ),
        migrations.AddIndex(
            model_name='hechocaso',
            index=models.Index(fields=['caso'], name='idx_hechos_casos_caso'),
        ),
        migrations.AddIndex(
            model_name='hechocaso',
            index=models.Index(fields=['hecho'], name='idx_hechos_casos_hecho'),
        ),
        migrations.AlterUniqueTogether(
            name='hechocaso',
            unique_together={('caso', 'hecho')},
        ),
        migrations.AddIndex(
            model_name='petitoriocaso',
            index=models.Index(fields=['caso'], name='idx_petitorios_casos_caso'),
        ),
        migrations.AddIndex(
            model_name='petitoriocaso',
            index=models.Index(fields=['petitorio'], name='idx_petitorios_casos_pet'),
        ),
        migrations.AlterUniqueTogether(
            name='petitoriocaso',
            unique_together={('caso', 'petitorio')},
        ),
    ]
