# Generated by Django 5.2.15 on 2026-09-18 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_casos', '0001_initial'),
        ('modulo_catalogo', '0007_jerarquia_nivel_anterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='rama_detectada',
            field=models.ForeignKey(blank=True, help_text='Rama jurídica del caso, seleccionada por el usuario al registrarlo (penal, civil, etc.). Nullable a nivel de BD solo para sobrevivir a on_delete=SET_NULL si la rama se elimina del catálogo más adelante; la creación de casos la exige (ver CasoCreateSerializer).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos', to='modulo_catalogo.ramaderecho'),
        ),
    ]
