# Generated by Django 5.2.15 on 2026-09-19 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_casos', '0002_alter_caso_rama_detectada'),
        ('modulo_catalogo', '0007_jerarquia_nivel_anterior'),
        ('modulo_clientes', '0005_cliente_hash_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('registrado', 'Caso registrado'), ('en_analisis', 'En análisis y estrategia'), ('investigacion_preliminar', 'Investigación preliminar'), ('denuncia_demanda', 'Denuncia / demanda presentada'), ('audiencias', 'En audiencias'), ('juicio', 'En juicio (etapa probatoria)'), ('sentencia', 'Sentencia emitida'), ('apelacion', 'Apelación / recursos'), ('cerrado', 'Cerrado / archivado')], max_length=40)),
                ('etapa_anterior', models.CharField(blank=True, choices=[('registrado', 'Caso registrado'), ('en_analisis', 'En análisis y estrategia'), ('investigacion_preliminar', 'Investigación preliminar'), ('denuncia_demanda', 'Denuncia / demanda presentada'), ('audiencias', 'En audiencias'), ('juicio', 'En juicio (etapa probatoria)'), ('sentencia', 'Sentencia emitida'), ('apelacion', 'Apelación / recursos'), ('cerrado', 'Cerrado / archivado')], help_text='Etapa en la que estaba el caso antes de este movimiento. Nula en la entrada inicial.', max_length=40, null=True)),
                ('nota', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'seguimientos_caso',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='caso',
            name='etapa',
            field=models.CharField(choices=[('registrado', 'Caso registrado'), ('en_analisis', 'En análisis y estrategia'), ('investigacion_preliminar', 'Investigación preliminar'), ('denuncia_demanda', 'Denuncia / demanda presentada'), ('audiencias', 'En audiencias'), ('juicio', 'En juicio (etapa probatoria)'), ('sentencia', 'Sentencia emitida'), ('apelacion', 'Apelación / recursos'), ('cerrado', 'Cerrado / archivado')], default='registrado', help_text="Etapa actual del proceso legal. Solo se modifica a través de seguimiento_service.registrar_seguimiento, que deja el historial en SeguimientoCaso. No confundir con 'estado' (activo/inactivo).", max_length=40),
        ),
        migrations.AddField(
            model_name='caso',
            name='etapa_actualizada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='caso',
            index=models.Index(fields=['etapa'], name='idx_casos_etapa'),
        ),
        migrations.AddField(
            model_name='seguimientocaso',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='modulo_casos.caso'),
        ),
        migrations.AddField(
            model_name='seguimientocaso',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_casos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='seguimientocaso',
            index=models.Index(fields=['caso', '-created_at'], name='idx_seguim_caso_fecha'),
        ),
    ]
