# Generated by Django 5.2.15 on 2026-09-24 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_casos', '0006_caso_eliminado_con_cliente'),
        ('modulo_catalogo', '0008_documento_norma'),
        ('modulo_clientes', '0006_papelera_clientes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='analisis_completado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='analisis_error',
            field=models.TextField(blank=True, help_text='Mensaje de la última corrida fallida. Se limpia al iniciar una nueva.', null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='analisis_iniciado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='analisis_iniciado_por',
            field=models.ForeignKey(blank=True, help_text='Quién disparó la corrida más reciente del análisis.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis_iniciados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caso',
            name='analisis_paso',
            field=models.CharField(blank=True, help_text='Paso actual del pipeline (chunking, embeddings, entidades, ranking...), solo informativo para la UI.', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='estado_analisis',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Con error')], default='pendiente', max_length=20),
        ),
        migrations.AddIndex(
            model_name='caso',
            index=models.Index(fields=['estado_analisis'], name='idx_casos_estado_analisis'),
        ),
    ]
