# Generated by Django 5.2.15 on 2026-10-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_casos', '0008_backfill_estado_analisis'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadocaso',
            name='jurisprudencia_estado',
            field=models.CharField(default='pendiente', max_length=40),
        ),
        migrations.AddField(
            model_name='resultadocaso',
            name='jurisprudencia_modelo_version',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
